include: "rules/references.smk"
include: "rules/busco.smk"


def generate_outputs():
    outputs = []

    outputs.append("references/references.ckpt")
    outputs.append("busco/lineage.txt")

    return outputs


rule all:
    input: generate_outputs()